---
title: F13dev 2
timezone: UTC
collections:
  future-releases:
    title: Future Releases
    output: true
  know-bugs:
    title: Known Bugs
    output: true
  pc-patches:
    title: PC Patches
    output: true
  ps4-patches:
    title: PS4 Patches
    output: true
  posts:
    title: Posts
    output: true
  released:
    title: Released
    output: true
  uploads:
    title: Uploads
    output: true
  xbox-one-patches:
    title: Xbox One Patches
    output: true
      
name: F13 Dev Notes
description: Developer notes for Friday the 13th
author: F13 Dev Notes
author_email: you@example.com
category_dir: "/"
baseurl: 
url: http://yourdomain.com/
permalink: pretty
paginate: 3
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
