---
title: F13dev 2
timezone: UTC
collections:
  know-bugs:
    title: Know Bugs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Sample Jekyll Blog
description: This is a sample Jekyll Blog.
author: Your Name
author_email: you@example.com
category_dir: "/"
baseurl: 
url: http://yourdomain.com/
permalink: pretty
paginate: 3
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
